### ISSUE TITLE
Some Questions About DeepSpeed

### ISSUE THREAD

**Issue by mushui-ty** [dyedd/deepspeed-diffusers#1]
In train_text_to_image.py, if use DeepSpeed to train Stable Diffusion on a single machine with multiple GPUs, and pass the unet model to deepspeed.initialize, will the frozen text_encoder (CLIP or T5) be automatically sharded across multiple GPUs?

**Comment by dyedd** [comment]
In my opinion, it won’t be sharded. Only the parts passed into `initialize` will be.

**Comment by mushui-ty** [comment]
> In my opinion, it won’t be sharded. Only the parts passed into `initialize` will be.

got it,  does it mean that if i want to shard the text encoder, i need to excecute another deepspeed.initialize and stop it's gradient

**Comment by dyedd** [comment]
> > In my opinion, it won’t be sharded. Only the parts passed into `initialize` will be.
> 
> got it, does it mean that if i want to shard the text encoder, i need to excecute another deepspeed.initialize and stop it's gradient

I think so, but I actually don't think it's necessary. If the text encoder is big, you can pre-encode the dataset, so the text encoder won't be involved. Also, I remember that models passed into `deepspeed.initialize` are typically those that need gradient updates, and I've never seen a program with two `deepspeed.initialize` calls.

**Comment by mushui-ty** [comment]
i've got it, thanks for reply
